import logging
from typing import Optional, Dict, Any
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
import anyio

from app.core.config import settings

logger = logging.getLogger(__name__)

async def add_calendar_event(
    event_title: str, 
    date_iso: str, 
    access_token: Optional[str] = None
) -> Dict[str, Any]:
    """
    Adds a deadline or election event to the user's primary Google Calendar.
    
    Args:
        event_title (str): The title of the event (e.g., 'Voter Registration Deadline').
        date_iso (str): The date of the event in ISO format (YYYY-MM-DD).
        access_token (Optional[str]): The Google OAuth access token.
        
    Returns:
        Dict[str, Any]: A result dictionary with 'status' or 'error'.
    """
    if access_token and access_token.startswith("Bearer "):
        access_token = access_token.replace("Bearer ", "").strip()

    if not access_token:
        return {
            "error": "Missing Google Calendar access token. Please sign in again and ensure Calendar permissions are granted."
        }

    creds = Credentials(token=access_token)

    try:
        # Wrap blocking Discovery API build in a thread
        service = await anyio.to_thread.run_sync(
            lambda: build("calendar", "v3", credentials=creds, cache_discovery=False)
        )

        event = {
            "summary": event_title,
            "description": f"Reminder generated by {settings.app_name}",
            "start": {
                "date": date_iso.split("T")[0],
                "timeZone": "UTC",
            },
            "end": {
                "date": date_iso.split("T")[0],
                "timeZone": "UTC",
            },
            "reminders": {
                "useDefault": False,
                "overrides": [
                    {"method": "email", "minutes": 24 * 60},
                    {"method": "popup", "minutes": 60},
                ],
            },
        }

        # Wrap blocking execution in a thread
        created_event = await anyio.to_thread.run_sync(
            lambda: service.events().insert(calendarId="primary", body=event).execute()
        )

        return {
            "status": "success",
            "message": f"Successfully added '{event_title}' to your Google Calendar.",
            "event_link": created_event.get("htmlLink"),
        }

    except HttpError as error:
        logger.error(f"Google Calendar API error: {error}")
        status_code = error.resp.status
        if status_code == 401:
            return {"error": "Calendar access token is expired or invalid. Please sign out and sign in again."}
        elif status_code == 403:
            return {"error": "Insufficient permissions. You did not grant Calendar access during sign-in."}
        return {"error": "Failed to add event to Google Calendar due to an API error."}
    except Exception as e:
        logger.error(f"Internal error adding calendar event: {str(e)}")
        return {"error": "Failed to access Google Calendar."}
