import asyncio
import logging
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

logger = logging.getLogger(__name__)


async def add_calendar_event(
    event_title: str, date_iso: str, access_token: str = None
) -> dict:
    """
    Adds a deadline or election event to the user's primary Google Calendar.
    
    Args:
        event_title: The title of the event (e.g., 'Voter Registration Deadline').
        date_iso: The date of the event in ISO format (YYYY-MM-DD).
    """
    if access_token and access_token.startswith("Bearer "):
        # Strip "Bearer " if it's passed with the prefix
        access_token = access_token.replace("Bearer ", "").strip()

    if not access_token:
        return {
            "error": "Missing Google Calendar access token. Please sign in again and ensure Calendar permissions are granted."
        }

    # Construct OAuth credentials object
    creds = Credentials(token=access_token)

    try:
        # Build the calendar service (this is blocking, so run in a thread or wrap in async if needed, but for simplicity here we just call it)
        # We use a short timeout where possible
        service = build("calendar", "v3", credentials=creds, cache_discovery=False)

        # Create the event object
        event = {
            "summary": event_title,
            "description": "Reminder generated by The Civic Navigator",
            "start": {
                "date": date_iso.split("T")[
                    0
                ],  # Format must be YYYY-MM-DD for all-day events
                "timeZone": "UTC",
            },
            "end": {
                "date": date_iso.split("T")[0],
                "timeZone": "UTC",
            },
            "reminders": {
                "useDefault": False,
                "overrides": [
                    {"method": "email", "minutes": 24 * 60},  # 24 hour reminder
                    {"method": "popup", "minutes": 60},
                ],
            },
        }

        # Execute request
        created_event = (
            service.events().insert(calendarId="primary", body=event).execute()
        )

        return {
            "status": "success",
            "message": f"Successfully added '{event_title}' to your Google Calendar.",
            "event_link": created_event.get("htmlLink"),
        }

    except HttpError as error:
        logger.error(f"Google Calendar API error: {error}")
        status_code = error.resp.status
        if status_code == 401:
            return {
                "error": "Calendar access token is expired or invalid. Please sign out and sign in again."
            }
        elif status_code == 403:
            return {
                "error": "Insufficient permissions. You did not grant Calendar access during sign-in."
            }
        else:
            return {
                "error": "Failed to add event to Google Calendar due to an API error."
            }
    except Exception as e:
        logger.error(f"Internal error adding calendar event: {str(e)}")
        return {"error": "Failed to access Google Calendar."}
